### ISSUE TITLE
Caught items not registerign properly

### ISSUE THREAD

**Issue by abrman** [MrKinau/FishingBot#11]
Just got a message in chat saying "FishingBot 2.4 - Caught "dirt"

I was just digging out some dirt in the area - guess it thought the entity from me digging was it's drop? Not sure if there is a workaround, but wanted to bring it into your attention :)

**Comment by MrKinau** [comment]
Well never had it on this state of the bot, but thanks for this information. Getting the fished item isnt fairly simple (currently I am using nearby items which dropped after a fish were caught with the highest velocity [normally the items are very fast when fished]).

Maybe this happened, because the bot havent fished anything (dunno if this is possible in vanilla, lol), I take the bug to my todos maybe I can replicate it. To test it I need some information of the server:
Which MC-Version is it on?
Which Serversoftware is it on? (Bukkit/Spigot/Sponge/Vanilla...)

**Comment by abrman** [comment]
Vanilla server, I was breaking a block aproximately 2-3 blocks above and 7 blocks both south and east. Happened several more times. The afk fishing room is below my storage room which I'm expanding, lol.

**Comment by MrKinau** [comment]
oh and thank you for reporting, I really appreciate it :)

**Comment by abrman** [comment]
Cheers! Thank you for the lovely tool! (Love that it's not a full on client and helps to keep areas loaded & be useful, the re-log is so beautiful!)

**Comment by MrKinau** [comment]
Sorry, but I wasnt able to reproduce this bug. I tested it with a vanilla 1.14.4 server with a full enchanted and a non-enchanted fishing rod mining dirt around the same location you mentioned. Maybe you can give more information on how to reproduce this bug (maybe a 100% reproduce guide?)
