### ISSUE TITLE
can't find the fishing rod in my backpack

### ISSUE THREAD

**Issue by 30266-Official** [MrKinau/FishingBot#150]
I have two fishing rods in my backpack, one of which is in my hand. But bot said he couldn't find the fishing rod.

2.7.17 1.16.5

**Comment by MrKinau** [comment]
This might happen if the inventory is sent after the bot wants to start. Normally the bot starts if found a new fishing rod later on. If it can't find a rod after some seconds you might need to disable the rod availability check (in the misc category), but most likely you do not have your inventory (maybe because of some anti bot plugin hiding your inventory)

**Comment by 30266-Official** [comment]
> 如果在机器人想要启动之后发送库存，则可能会发生这种情况。通常，如果稍后找到新的钓鱼竿，机器人就会启动。如果几秒钟后它找不到钓竿，您可能需要禁用钓竿可用性检查（在其他类别中），但很可能您没有库存（可能是因为某些反机器人插件隐藏了您的库存）

**Comment by 30266-Official** [comment]
Thank you. This problem did not appear on 2.7.15
The button is too close(x
