### ISSUE TITLE
Password HASHING !!!!!

### ISSUE THREAD

**Issue by Izocel** [MrKinau/FishingBot#170]
come on dude ;)

Also did you consider to launch multiple bot with the same config file ;)

**Comment by MrKinau** [comment]
A hash is irreversible. The password in the config needs to be used in later usages (although you want to re-enter it every time).
Hasing is not useful. Whats been done in the mojang launcher is that the password is encrypted with a key. This can be done, but has almost no effect, because the needs be stored somewhere safe which is highly platform specific.
The code is a mess. Starting multiple bots is not a planned features, but obv. you can start the whole application multiple times with the config set as a [command line parameter](https://github.com/MrKinau/FishingBot/wiki/Command-Line-Options).

**Comment by Izocel** [comment]
Yes thats true for the hash didn't think about the auto-start procedure...

And for multiple, i've starded a folder structure but could we pass user and pass as parameter with config file so i could have a slave.config file and a master.config file ?? :)

**Comment by Izocel** [comment]
![image](https://user-images.githubusercontent.com/68454661/178076164-4e11d8d7-69cb-4140-b673-88f55602a04f.png)

**Comment by MrKinau** [comment]
This can be done with the docker setup, but it's not documented at all (currently). If you know how to use docker compose, you can simply clone the repo, build the container and set the options using the docker compose file or command line. Otherwise you may. If you have an accesstoken you can also set the account file with the `accountfile` command line parameter.

**Comment by Izocel** [comment]
Ok thanks i'll look at that if contuning like that is a pain but should do the job once i've run a couple tests ;)
