### ISSUE TITLE
Auto-reconnect not working properly

### ISSUE THREAD

**Issue by Flynn-Mandrake** [MrKinau/FishingBot#19]
On the server I'm on we have an agreement to kick the bot when other players want to sleep (ingame). This is supposed to work on the premise that the bot automatically reconnects 20 or so seconds after being kicked, but that isn't the case, as it just spews out a bunch of
`[SEVERE ] Error while trying to send: PacketOutPosition`
with the occasional
`java.net.SocketException: Connection reset`
instead of properly connecting (although that second one doesn't seem to be related to the actual problem. I did some testing, and it seems to actually manage to connect to the server, but the error messages just keep on coming instead of it actually starting to fish. It might be noteworthy that I'm running the bot on a Raspberry Pi 3.

**Comment by Flynn-Mandrake** [comment]
Update: It actually seems to work properly, but it still keeps spamming `[SEVERE ] Error while trying to send: PacketOutPosition`.

**Comment by MrKinau** [comment]
Thank you for your issue report. I already noticed this spamming, which occurs, because the bot updates its position every second and this task will not be interrupted after the bot gets disconnected (this should be fixed). Seems like the reconnect works for you now, but it still spams the message? Will the message only be spammed between disconnected and reconnected state or will it still be spammed after connected again?

**Comment by Flynn-Mandrake** [comment]
It will still be spammed after the bot has properly reconnected to the server again.

**Comment by MrKinau** [comment]
okay will fix it, if I have enough time. Thanks for reporting

**Comment by MrKinau** [comment]
hopefully everything fixed in the latest comment. re-create if you still have issues :)
