### ISSUE TITLE
Can't make bot work

### ISSUE THREAD

**Issue by Moralex2000** [MrKinau/FishingBot#21]
I filled in the Config.properties.
I changed the account-username and account-password to the informations of my minecraft account, changed the default protocol to 1.15 and the server ip to the ip of my server (its a minehut server).
I ran the fishinbot.jar trought the cmd, but the bot didn't seem to work.
Here is the log: [log0.log](https://github.com/MrKinau/FishingBot/files/3993138/log0.log)

I probably just don't know how to properly set the bot up, but I tried changing everything i could in the Config.properties and i couldn't figure it out, so I'm seeking help

**Comment by MrKinau** [comment]
Hey Moralex.
Thanks for your issue. I am happy to see you are interested in the bot. In applied logfile there are no changed config values. The config file is just default for the bot? Please try to just change username (your Account-Mail) password and server-ip and try again.
Also make sure the bot has access to the config file and don't rename the generated config file.

Additional information: I am not completely up to date with the protocol versions. I think 1.15.1 is already out and this version is not implemented yet (it may also work on this version, but it's not tested)

**Comment by Moralex2000** [comment]
But I did change the config values (I wont attach it here as it contains my minecraft login credentials)

**Comment by MrKinau** [comment]
Atm I can only help you with telling you to try everything again. Delete everything except the jar and rerun the bot. I will take a close look on it tomorrow (CET) maybe you can send a CENSORED version of your config and send the whole logs folder.

**Comment by Moralex2000** [comment]
Tried deleting and rerunning the bot to refill the config.properties, but sadly it didn't work

[config+log.zip](https://github.com/MrKinau/FishingBot/files/3993192/config%2Blog.zip)

Had to make it a zip folder or it would not send

**Comment by MrKinau** [comment]
Well I'm tested a little bit around and I really dont know why it does not work for you.

The log should be something like this [log1.log](https://github.com/MrKinau/FishingBot/files/3994582/log1.log) as it is on my local machine.

On the first start it should look like this (because the config is not created) 
[log0.log](https://github.com/MrKinau/FishingBot/files/3994587/log0.log)

On first startup in the console messages like `Undefined config option in config.properties -> server-ip` should appear. This should only be if the config is not created yet. If this happens every time the jar file has no read-access to the config file. In that case you should try to use a different drive (if you are under Windows) or check the permissions of the config file and the ownership of the jar and config files (mainly unix systems).

I hope I could help you solving this issue and would be happy to hear if it works for you!

**Comment by Moralex2000** [comment]
I had the bot in D: and moved it to C: (deleted everything but the jar file). When i ran it for the first time (java -jar C:\FishingBot\Fishingbot.jar) it didn't create the config.properties or the log file

**Comment by Moralex2000** [comment]
I think I figured out what is the problem, the jar was creating two config.properties, one in the folder the jar file was and other in the users file (C:/Users/PC). I was editing the one in the bot file, but it was reading the one in the user file. After editing the one in the user file it worked like a charm, thanks for your help and sorry for the trouble

**Comment by Moralex2000** [comment]
Just a quick question, can I use the minecraft account that I put in the bot while it is fishing?

**Comment by MrKinau** [comment]
You can use it, but of course not on the same server. If the bot (for some reason) disconnects it might not correctly reconnects, because the session is invalid.

**Comment by Moralex2000** [comment]
tried using the bot again a few hours later, but i keep geting  "Bot is slow (maybe stuck). Trying to restart!"

**Comment by MrKinau** [comment]
The bot needs to be equipped with a fishing rod standing in front of water. If the rod is fully enchanted this message should only rarely appear. This message appears if the bot haven't caught anything for one minute

**Comment by Moralex2000** [comment]
i got luring 2 on my fishing rod but i keep getting the "bot is slow"message

**Comment by MrKinau** [comment]
As long as it still is fishing it's no problem and you can ignore this warning
