### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by nutjob4life** [MrKinau/FishingBot#215]
Currently, `FishingBot-2.10.6` reports:

    Login failed: {"translate":"multiplayer.disconnect.incompatible","with":["1.20.2"]}

Now that 1.20.2 has been pushed to Realms, it'd be just lovely to have the computer do my anglin' for me while I do the easy work of enjoying all that fish and loot 😌

(Patreon supporter name: `PT`)

**Comment by MrKinau** [comment]
Thanks for your reminder. Currently I am busy work-arounding all the new bugs (https://bugs.mojang.com/browse/MC-265463, https://bugs.mojang.com/browse/MC-265462) for the server I work for, but once that done I'll take a look on it (might take some time, as I've not started and it might be a bigger update, due to the ton of networking changes of this release)

**Comment by nutjob4life** [comment]
@MrKinau absolutely no rush. My friends and I play strictly for fun and friendship 😁

**Comment by nutjob4life** [comment]
Hi @MrKinau! Checking in to see if we've carved out some time for progress on this?

**Comment by MrKinau** [comment]
I'm not done yet. As 1.20.2 made many changes like NBT Parsing Changes or the new configuration phase, it's not an easy update, but I hope I'll find enough time to finish next weekend. I've firstly updated some translations and looked into apple silicon support.

**Comment by chromeeh** [comment]
Curious about the new update, as the Fishing Bot is a real helper!

**Comment by MrKinau** [comment]
Merged with #222 :)

**Comment by nutjob4life** [comment]
Working great! Thank you so much!
