### ISSUE TITLE
Implement realm connection

### ISSUE THREAD

**Issue by thibbo** [MrKinau/FishingBot#5]
Hi,
Thanks for your fishing bot. I wonder how to use it on a realm server

**Comment by MrKinau** [comment]
Currently there is (maybe) no support for realms. I never used realms and I am not comfortable using it. Maybe I can implement such a feature, but I am not sure, because it may depends on Mojang APIs I dont know and maybe not allowed to publish, but over the next days I will take a closer look at it.

**Comment by MrKinau** [comment]
Just read into the realms API and it seems to be fairly easy possible for me to implement such a feature. Working on it for now.

**Comment by MrKinau** [comment]
implemented in v2.4
