### ISSUE TITLE
Bot Disconnects

### ISSUE THREAD

**Issue by Sebayop** [MrKinau/FishingBot#63]
I was trying to connect the bot to a server, in the lobby it logs in and everything is fine, but when it connects to survival it starts to fish and disconnects automatically
here is my log and settings, it is a paper server with bungeecord

![Solar-PuTTY_TDYlhcZKn1](https://user-images.githubusercontent.com/69135014/89148213-3225cb80-d527-11ea-939e-7e642d3e3c9c.png)
![Solar-PuTTY_h1v6kXDJ0F](https://user-images.githubusercontent.com/69135014/89148295-69947800-d527-11ea-806e-ae289d5fb3f9.png)

**Comment by MrKinau** [comment]
Thanks for your issue.
As described in the disconnect Message. You are may sending an empty message. Seems Like there is a line break after the start-text following an empty line?

**Comment by Sebayop** [comment]
![image](https://user-images.githubusercontent.com/69135014/89154608-2f31d780-d535-11ea-934e-4c1c95b54243.png)
There are no empty spaces after the text

**Comment by MrKinau** [comment]
Sorry I can not explain why you get kicked, maybe you can upload a CENSORED copy of your full config file? Maybe there are strange characters in? Haven't got this issue before :/

**Comment by Sebayop** [comment]
[config.txt](https://github.com/MrKinau/FishingBot/files/5018522/config.txt)

**Comment by MrKinau** [comment]
Thanks for your patience.
Oh well that took a while to find the issue. Now I am sure I got it.

The problem is that the bot tries to send the empty message you set in announce-lvl-up. As the message is empty you get kicked by spigot, because it is not allowed to send empty messages. This lvl-up message will also be sent on join, so the bot just get kicked on every connection attempt.

To fix this: You can type "false" in announce-lvl-up (without the ""). I forgot to mention it in the header of the config, I'll fix this.

I'm pretty sure thats it, but if not be welcome to answer again and I will take a much closer look at it.

Last, but not least: You do not need the /trigger Bot. It's just an example command to show that start-text also works with commands.

**Comment by Sebayop** [comment]
oh I hadn't noticed that, now it works thank you very much

**Comment by MrKinau** [comment]
np :)
