### ISSUE TITLE
 Unable to log in multiple accounts at the same time

### ISSUE THREAD

**Issue by MCwenka** [MrKinau/FishingBot#65]
When I tried to access the same server with two accounts, I found that although they were fishing, if one of the accounts had a fish bite, the two accounts would lift the fishing rod at the same time. Does that mean I can only log in to one account on one computer？

**Comment by MrKinau** [comment]
Thanks for your issue.
This should not happen. The bot is developed to avoid this bug and therefore it does not just wait for the fishing sound, it should wait for his bobber getting extra-velocity. Maybe this part gets broken during updates (haven't tested it since a while). I will test it and fix it asap if I can verify this issue.

**Comment by MrKinau** [comment]
Well I'm sorry, but I am not able to reproduce this. Even with two bots starting at the same time fishing I can not reproduce this. I can't explain why it does not work for you :/ Maybe some facts can help with this?

How do you start the two (or more) bots? (+ which operating system do you use? Windows?)
Which version of the bot do you use? (hopefully 2.7.3)
Which version of Minecraft do you target?

**Comment by Oopas** [comment]
I initially used an old version of 2019, and I tried 2.7.3 again, and it worked very well.
Thank you for your development😍

**Comment by MCwenka** [comment]
I'm so sorry...
I initially used an old version of 2019, and I tried 2.7.3 again, and it worked very well.
Thanks for your help
