### ISSUE TITLE
im getting a error

### ISSUE THREAD

**Issue by hdhdhfhfirjf** [MrKinau/FishingBot#77]
not sure whats causing this but im recieving a error "Could not receive packet! Shutting down!" when trying to connect to the server could you possibly help fix this

**Comment by MrKinau** [comment]
https://github.com/MrKinau/FishingBot/wiki/Troubleshooting may help you. If you need faster support you can join the Discord https://discord.gg/cuHADe5 

The error you applied could be everything. It would help to get the full log (logs/log0.log)

**Comment by hdhdhfhfirjf** [comment]
[log0.log](https://github.com/MrKinau/FishingBot/files/5320549/log0.log)

the log doesnt say anything that hasnt been told to you im not sure whats causing this error

**Comment by MrKinau** [comment]
Okay, indeed this looks like a bug. You may try connecting with a newer  protocol version (change the protocol-version in the config to something newer e.g. 1.16.3). As it seem to be an issue with the protocol, a newer version might work. Please let me know if this fixes your issue, otherwise I'll take a closer look on it tomorrow (CET)

**Comment by hdhdhfhfirjf** [comment]
connected with 1.16.3 no problem thank you brother.

**Comment by MrKinau** [comment]
Okay great, then I'll close this issue.
